import React, { useEffect, useState } from 'react';
import './Card.css';
import logo2 from './images/logo2.png';
import man from './images/man.jpg';
import axios from 'axios';
import { Preview, print } from 'react-html2pdf';

export default function Card() {
    const [latestEntry, setLatestEntry] = useState(null);

    useEffect(() => {
        axios.get('http://localhost:3001/form')
            .then(res => {
                console.log('API Response:', res.data);
                const data = res.data || [];
                const latestEntry = data.length > 0 ? data[data.length - 1] : null;

                console.log('Latest Entry:', latestEntry);
                setLatestEntry(latestEntry);
            })
            .catch(err => console.error('API Error:', err));
    }, []);

    return (
        <div>
            <div className="card-body">
                <Preview id={'jsx-template'}>
                    <div className="card">
                        <div className="title">
                            <img src={logo2} alt="logo" />
                            <h3>Ticket Trove</h3>
                        </div>
                        <div className="content">
                            <div className="photo">
                                <img src={man} alt="" width="120px" height="100px" />
                            </div>
                            <div className="unorder">
                                {latestEntry ? (
                                    <ul key={latestEntry.id}>
                                        <li>Name: {latestEntry.Name}</li>
                                        <li>ID: {latestEntry.id}</li>
                                        <li>Source: {latestEntry.Source}</li>
                                        <li>Destination: {latestEntry.Destination}</li>
                                        <li>Address: {latestEntry.Address}</li>
                                        <li>Validity Date: {latestEntry.ValidityDate}</li>
                                    </ul>
                                ) : (
                                    <p>No data available.</p>
                                )}
                            </div>
                        </div>
                        <div className="foot">
                            <h3 style={{textAlign:'center'}}>Pass Generated by Ticket Trove</h3>
                        </div>
                    </div>
                </Preview>
                
                <button onClick={() => print('card', 'jsx-template')} className='download-button'>Print</button>
            </div>
        </div>
    );
}