import React, { useEffect, useState } from 'react';
import './Renewal.css';
import axios from 'axios';
import logo2 from './images/logo2.png';
import man from './images/man.jpg'; 
import { Preview, print } from 'react-html2pdf'; 
export default function Renewal() {
  const [Id, setId] = useState('');
  const [detail, setDetail] = useState(null);
  const [message, setMessage] = useState('');

  useEffect(() => {
    if (Id) {
      axios
        .get(`http://localhost:3001/form/${Id}`)
        .then(res => {
          const data = res.data;
          setDetail(data);

          const now = new Date();
          const currentMonth = now.getMonth() + 1; 
          const currentYear = now.getFullYear();

          const validityDate = new Date(data.ValidityDate);
          if (validityDate.getMonth() + 1 === currentMonth && validityDate.getFullYear() === currentYear) {
            setMessage('No need to renew the pass.');
          } else {
            const nextMonthFirstDay = new Date(currentYear, currentMonth, 1);
            const updatedValidityDate = nextMonthFirstDay.toISOString().split('T')[0];

            axios
              .put(`http://localhost:3001/form/${Id}`, { ValidityDate: updatedValidityDate })
              .then(() => {
                setMessage('Pass renewed for the next month.');
                setDetail({ ...data, ValidityDate: updatedValidityDate });
              })
              .catch(err => console.error(err));
          }
        })
        .catch(err => console.error(err));
    }
  }, [Id]);

  const handleSubmit = (e) => {
    e.preventDefault();
    setMessage('');
    setDetail(null); 
  };

  return (
    <>
      <div className="header2">
        <h2>Renewal Form</h2>
      </div>
      <div className="renewal">
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="BusPass ID"
            value={Id}
            onChange={(e) => setId(e.target.value)}
          />
          <button type="submit">Submit</button>
        </form>
        {message && <p className="message">{message}</p>}
        {detail && (
          <div className="card-body">
            <Preview id={'jsx-template'}>
              <div className="card">
                <div className="title">
                  <img src={logo2} alt="logo" />
                  <h3>Ticket Trove</h3>
                </div>
                <div className="content">
                  <div className="photo">
                    <img src={man} alt="Profile" width="120px" height="100px" />
                  </div>
                  <div className="details-list">
                    <p><strong>ID:</strong> {detail.id}</p>
                    <p><strong>Name:</strong> {detail.Name}</p>
                    <p><strong>Source:</strong> {detail.Source}</p>
                    <p><strong>Destination:</strong> {detail.Destination}</p>
                    <p><strong>Validity Date:</strong> {detail.ValidityDate}</p>
                  </div>
                </div>
                <div className="foot">
                  <h3>Pass Generated by Ticket Trove</h3>
                </div>
              </div>
            </Preview>
            <button onClick={() => print('card', 'jsx-template')} className='download-button'>
              Print
            </button>
          </div>
        )}
      </div>
    </>
  );
}